In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a+b)
print(a*b)

[6 6 6 6 6]
[5 8 9 8 5]


In [7]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [8]:
print(x.shape)

(2, 2)


In [10]:
print(a.ndim)

1


In [11]:
print(x.dtype)

int32


In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,21)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [14]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
np.random.randint(10,40, size=(3,5))

array([[27, 13, 33, 29, 38],
       [31, 19, 34, 33, 15],
       [23, 15, 20, 13, 28]])

In [16]:
x = np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])

y = np.array([[1,8,3],
            [3,7,2],
            [2,5,3]])

print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [17]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [ ]:
#matrix multiplication
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [19]:
#matrix multiplication
print(x.dot(y))

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [ ]:
x.prod() #product of all elements

12600

In [21]:
x.sum() #sum of all elements

30

In [22]:
x.mean() #mean of all elements

3.3333333333333335

In [23]:
x.mean(axis=0) #mean of each column

array([4., 4., 2.])

In [24]:
x.mean(axis=1) #mean of each row

array([4., 3., 3.])

In [25]:
print(x.var()) #variance of all elements
print(x.std()) #standard deviation of all elements
print(x.min()) #minimum of all elements

3.3333333333333335
1.8257418583505538
1


In [26]:
z = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(z, 25)) #25th percentile
print(np.percentile(z, 50)) #50th percentile
print(np.percentile(z, 75)) #75th percentile

3.0
5.0
7.0


In [27]:
arr = np.array([[16,44,46,49],[10,22,41,35],[11,35,20,12],[46,33,41,36]])
print(arr)

[[16 44 46 49]
 [10 22 41 35]
 [11 35 20 12]
 [46 33 41 36]]


In [28]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[16 44]
 [46 49]
 [10 22]
 [41 35]
 [11 35]
 [20 12]
 [46 33]
 [41 36]]


In [29]:
print('2x8')
print(arr.reshape(2,8))

2x8
[[16 44 46 49 10 22 41 35]
 [11 35 20 12 46 33 41 36]]
